### ISSUE TITLE
Epic: Lesson overhaul

### ISSUE THREAD

**Issue by TheUnlocked** [TheUnlocked/Necode#38]
Relevant issues:
- #7 
- #8 
- #13
- #15
- #24 

# API Changes
- [x] `ActivityEntity`
    - Add field `displayName: string`

# Backend changes
- [x] Remove length limits for lesson names
- [x] `/api/classroom/[classroomId]/lesson/[lessonId]`
    - Remove `PUT`
    - Add `PATCH`
         - Add query parameter `merge?: 'replace' | 'combine'`
         - Body:
           ```js
           {
               date?: IsoDate;
               displayName?: string;
           }
           ```
        - If `date` is set and there is already a lesson on `date`:
            - If there are no activities in the lesson on `date`, delete it (`merge` does not need to be set).
            - If `merge` is not set or set to `'reject'`, throw a `409 CONFLICT`
            - If `merge` is `'replace'`, delete the existing lesson on `date`.
            - If `merge` is `'combine'`, append the activities from the lesson on `date` to the target lesson, then delete the lesson on `date`.
        - Returns the lesson entity, subject to the `include` query parameter.
- [x] `/api/classroom/[classroomId]/lesson/[lessonId]/activity`
    - Update `POST`
        - Add `displayName: string` field.
- [x] `/api/classroom/[classroomId]/activity/[activityId]`
    - Rename `PUT` to `PATCH`
        - Body:
           ```js
           {
               configuration?: JsonObject;
               enabledLanguages?: string[];
               displayName?: string;
               lesson?: EntityId<LessonEntity>;
               order?: number;
           }
           ```
        - The `order` field indicates the spot the activity should end up in (i.e. the index of the activity to insert before).
            - If `lesson` is included and `order` is omitted, the activity should go to the end of the target lesson.
        - Returns the activity entity, subject to the `include` query parameter.

# Frontend changes

All changes are to `/classroom/[classroomId]/manage`

No more clever attempts to aggregate changes.
- [x] Issue a `POST` immediately when an activity is created, and do not allow editing it until a response is received.
- [x] Issue a `PATCH` request on _every_ change. For changing text, only commit changes on blur.
    - It is okay to allow editing while these requests are going through, but client-side changes should be rolled back if the request fails.

Dragging activities
- [x] Moving an activity to another lesson
    - [x] Allow dragging to a day on the calendar
        - [x] If holding ctrl, copy to instead
    - Allow dragging to a "move" button (like with deleting), which opens a dialog with a calendar picker ⚠ Removed

Editing activities
- [x] Allow dragging to a "clone" button (like with deleting) which adds a copy of the dragged activity to the lesson
- [x] Turn activity display names into text fields
- [x] Make activity display names align with the displayName field in the entity

Dragging Lessons
- [x] Move a lesson to another date
    - [x] If holding ctrl, copy to instead
    - [x] If there is already a lesson on the target date, ask for confirmation with an option for merge type (replace/combine)
- [x] Drag onto delete button to delete (with confirmation dialog)

**Comment by TheUnlocked** [comment]
All tasks done, just need to go through basic functionality unrelated to this feature to make sure there are no regressions.
